"""20181015_init

Revision ID: d96604579afb
Revises: 
Create Date: 2018-10-15 15:56:58.124869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96604579afb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('register_time', sa.Integer(), nullable=True),
    sa.Column('permission', sa.SmallInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('country', sa.CHAR(length=40), nullable=True),
    sa.Column('avatar', sa.CHAR(length=180), nullable=True),
    sa.Column('register_ip', sa.CHAR(length=17), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('login_inc', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_expire_time'), 'user', ['expire_time'], unique=False)
    op.create_index(op.f('ix_user_login_inc'), 'user', ['login_inc'], unique=False)
    op.create_index(op.f('ix_user_register_time'), 'user', ['register_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_register_time'), table_name='user')
    op.drop_index(op.f('ix_user_login_inc'), table_name='user')
    op.drop_index(op.f('ix_user_expire_time'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
