"""empty message

Revision ID: 2bcd0b28737e
Revises: 
Create Date: 2019-01-03 18:34:07.232783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcd0b28737e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=120), nullable=True),
    sa.Column('user_name', sa.String(length=10), nullable=True),
    sa.Column('password', sa.CHAR(length=32), nullable=True),
    sa.Column('is_super', sa.SmallInteger(), nullable=False),
    sa.Column('active', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_mail'), 'user', ['mail'], unique=False)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_mail'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
