application:
    template_path: templates
    static_path: static
    cookie_secret: QiNDQXm6peOfl1VOGhdLoZ0f3ZucyEg6psGNLu1tWZE=
    debug: true

security_key: QiNDQXm6peOfl1VOGhdLoZ0f3ZucyEg6psGNLu1tWZE=
httpserver:
    xheaders: true

server:
    domain: localhost
    name: thor
    port: 6789
    expire_time: 3600
    back_ip: 127.0.0.1
    pass_mixin: 0x00544
    cookie_name:
        user_id: u_u
        parameters: o_o

worker:
    mode: false

auth_storage:  JWT 


celery:
    backend: 'redis://:pdfonline2018@vhost_redis:6379/10' 
    broker: 'amqp://pdfonline:pdfonline2018@vhost_rabbitmq:5672//' 
    sleep_time: 0.05

database:
    mysql: 'mysql+mysqldb://pecloud:Wshare2015#@vhost_mysql:3306/mytest?charset=utf8'
    mongo:
        client: 'mongodb://esign:pe123123@vhost_mysql' 
        db: 'mytest'
        session_key: user_id

debug: true
